# -*- coding: utf-8 -*-
{
    'name': "Employee SIIC Customization",
    'summary': """  Custom Application for Employee SIIC Customization """,
    'description': """ Employee SIIC Customization  """,
    'author': "SIIC",
    'category': 'Human Resources/Employees',
    'depends': ['base', 'multi_branch', 'hr'],
    'data': [
        "security/course_security.xml",
        # 'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/ir_cron.xml',
        'views/hr_employee.xml',
        "views/hr_course_category_views.xml",
        "views/hr_course_views.xml",
        "views/hr_employee_views.xml",
        "views/hr_employee_mobile_number.xml",
    ],
    'images': ['static/description/icon.png'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
